[build]
  # Build command (optional, since this is a static site)
  command = "npm run build"
  # Directory to publish
  publish = "."

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; font-src 'self' data:; object-src 'none'; media-src 'self' blob:; worker-src 'self' blob:;"

# Cache headers for static assets
[[headers]]
  for = "/src/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/src/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/src/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for HTML
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects for SPA behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Force HTTPS redirect
[[redirects]]
  from = "http://pdfsplit.netlify.app/*"
  to = "https://pdfsplit.netlify.app/:splat"
  status = 301
  force = true

# Forms configuration (if needed for feedback)
[forms]
  # Enable Netlify Forms
  enabled = true